[package]
name = "test_zip"
version = "0.1.0"
edition = "2021"
publish = ["meuse"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.6.2"
hyper = "0.14"

